// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	domain "github.com/Ermi9s.Golang-Learning-phase/Testing-TaskManager/domain"
	mock "github.com/stretchr/testify/mock"
)

// Task_Repository_interface is an autogenerated mock type for the Task_Repository_interface type
type Task_Repository_interface struct {
	mock.Mock
}

// DeleteTaskDocument provides a mock function with given fields: id
func (_m *Task_Repository_interface) DeleteTaskDocument(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTaskDocument")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTaskDocumentByFilter provides a mock function with given fields: filter
func (_m *Task_Repository_interface) GetTaskDocumentByFilter(filter map[string]string) ([]domain.Task, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskDocumentByFilter")
	}

	var r0 []domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]string) ([]domain.Task, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(map[string]string) []domain.Task); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]string) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaskDocumentById provides a mock function with given fields: id
func (_m *Task_Repository_interface) GetTaskDocumentById(id string) (domain.Task, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskDocumentById")
	}

	var r0 domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (domain.Task, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) domain.Task); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertTaskDocument provides a mock function with given fields: object
func (_m *Task_Repository_interface) InsertTaskDocument(object domain.Task) (string, error) {
	ret := _m.Called(object)

	if len(ret) == 0 {
		panic("no return value specified for InsertTaskDocument")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.Task) (string, error)); ok {
		return rf(object)
	}
	if rf, ok := ret.Get(0).(func(domain.Task) string); ok {
		r0 = rf(object)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(domain.Task) error); ok {
		r1 = rf(object)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTaskDocumentById provides a mock function with given fields: id, update
func (_m *Task_Repository_interface) UpdateTaskDocumentById(id string, update domain.Task) error {
	ret := _m.Called(id, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskDocumentById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, domain.Task) error); ok {
		r0 = rf(id, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTask_Repository_interface creates a new instance of Task_Repository_interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTask_Repository_interface(t interface {
	mock.TestingT
	Cleanup(func())
}) *Task_Repository_interface {
	mock := &Task_Repository_interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
