// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Services is an autogenerated mock type for the Services type
type Services struct {
	mock.Mock
}

// Encode provides a mock function with given fields: id, email, is_admin
func (_m *Services) Encode(id string, email string, is_admin bool) (string, error) {
	ret := _m.Called(id, email, is_admin)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, bool) (string, error)); ok {
		return rf(id, email, is_admin)
	}
	if rf, ok := ret.Get(0).(func(string, string, bool) string); ok {
		r0 = rf(id, email, is_admin)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, bool) error); ok {
		r1 = rf(id, email, is_admin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HashPassWord provides a mock function with given fields: spass
func (_m *Services) HashPassWord(spass string) string {
	ret := _m.Called(spass)

	if len(ret) == 0 {
		panic("no return value specified for HashPassWord")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(spass)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewServices creates a new instance of Services. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServices(t interface {
	mock.TestingT
	Cleanup(func())
}) *Services {
	mock := &Services{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
