// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	domain "github.com/Ermi9s.Golang-Learning-phase/Testing-TaskManager/domain"
	mock "github.com/stretchr/testify/mock"
)

// Task_Usecase_interface is an autogenerated mock type for the Task_Usecase_interface type
type Task_Usecase_interface struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: model, user_id
func (_m *Task_Usecase_interface) CreateTask(model domain.Task, user_id string) (string, error) {
	ret := _m.Called(model, user_id)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.Task, string) (string, error)); ok {
		return rf(model, user_id)
	}
	if rf, ok := ret.Get(0).(func(domain.Task, string) string); ok {
		r0 = rf(model, user_id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(domain.Task, string) error); ok {
		r1 = rf(model, user_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTask provides a mock function with given fields: id
func (_m *Task_Usecase_interface) DeleteTask(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTask provides a mock function with given fields: id
func (_m *Task_Usecase_interface) GetTask(id string) (domain.Task, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (domain.Task, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) domain.Task); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTasks provides a mock function with given fields: filter
func (_m *Task_Usecase_interface) GetTasks(filter map[string]string) ([]domain.Task, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetTasks")
	}

	var r0 []domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]string) ([]domain.Task, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(map[string]string) []domain.Task); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]string) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTask provides a mock function with given fields: id, model
func (_m *Task_Usecase_interface) UpdateTask(id string, model domain.Task) (domain.Task, error) {
	ret := _m.Called(id, model)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string, domain.Task) (domain.Task, error)); ok {
		return rf(id, model)
	}
	if rf, ok := ret.Get(0).(func(string, domain.Task) domain.Task); ok {
		r0 = rf(id, model)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}

	if rf, ok := ret.Get(1).(func(string, domain.Task) error); ok {
		r1 = rf(id, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTask_Usecase_interface creates a new instance of Task_Usecase_interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTask_Usecase_interface(t interface {
	mock.TestingT
	Cleanup(func())
}) *Task_Usecase_interface {
	mock := &Task_Usecase_interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
