// Code generated by mockery v2.44.1. DO NOT EDIT.
package repositorymoke

import (
	domain "github.com/Ermi9s.Golang-Learning-phase/Testing-TaskManager/domain"
	mock "github.com/stretchr/testify/mock"
)

// Repository_interface is an autogenerated mock type for the Repository_interface type
type Repository_interface struct {
	mock.Mock
}

// DeleteTaskDocument provides a mock function with given fields: id
func (_m *Repository_interface) DeleteTaskDocument(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTaskDocument")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUserDocument provides a mock function with given fields: id
func (_m *Repository_interface) DeleteUserDocument(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserDocument")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTaskDocumentByFilter provides a mock function with given fields: filter
func (_m *Repository_interface) GetTaskDocumentByFilter(filter map[string]string) ([]domain.Task, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskDocumentByFilter")
	}

	var r0 []domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]string) ([]domain.Task, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(map[string]string) []domain.Task); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]string) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaskDocumentById provides a mock function with given fields: id
func (_m *Repository_interface) GetTaskDocumentById(id string) (domain.Task, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskDocumentById")
	}

	var r0 domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (domain.Task, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) domain.Task); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserDocumentByFilter provides a mock function with given fields: filter
func (_m *Repository_interface) GetUserDocumentByFilter(filter map[string]string) ([]domain.User, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetUserDocumentByFilter")
	}

	var r0 []domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]string) ([]domain.User, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(map[string]string) []domain.User); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]string) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserDocumentById provides a mock function with given fields: id
func (_m *Repository_interface) GetUserDocumentById(id string) (domain.User, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserDocumentById")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (domain.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) domain.User); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertTaskDocument provides a mock function with given fields: object
func (_m *Repository_interface) InsertTaskDocument(object domain.Task) (string, error) {
	ret := _m.Called(object)

	if len(ret) == 0 {
		panic("no return value specified for InsertTaskDocument")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.Task) (string, error)); ok {
		return rf(object)
	}
	if rf, ok := ret.Get(0).(func(domain.Task) string); ok {
		r0 = rf(object)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(domain.Task) error); ok {
		r1 = rf(object)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertUserDocument provides a mock function with given fields: object
func (_m *Repository_interface) InsertUserDocument(object domain.User) (string, error) {
	ret := _m.Called(object)

	if len(ret) == 0 {
		panic("no return value specified for InsertUserDocument")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.User) (string, error)); ok {
		return rf(object)
	}
	if rf, ok := ret.Get(0).(func(domain.User) string); ok {
		r0 = rf(object)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(domain.User) error); ok {
		r1 = rf(object)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTaskDocumentById provides a mock function with given fields: id, update
func (_m *Repository_interface) UpdateTaskDocumentById(id string, update domain.Task) error {
	ret := _m.Called(id, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskDocumentById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, domain.Task) error); ok {
		r0 = rf(id, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserDocumentById provides a mock function with given fields: id, update
func (_m *Repository_interface) UpdateUserDocumentById(id string, update domain.User) error {
	ret := _m.Called(id, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserDocumentById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, domain.User) error); ok {
		r0 = rf(id, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository_interface creates a new instance of Repository_interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository_interface(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository_interface {
	mock := &Repository_interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
